name: Build

on:
  push:
    branches:
      - finalproject
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clones superficiais devem ser desativados para análise completa
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectKey: "AndrezaH_ProjetoFinal"     # <- adicione seu projectKey aqui
          organization: "Aandrezah"                # <- adicione sua organização aqui
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
